### ISSUE TITLE
Misleading installation instructions

### ISSUE THREAD

**Issue by kl0tl** [purescript-contrib/purescript-argonaut-generic#28]
**Is your change request related to a problem? Please describe.**
The README suggests that this package can be installed with `spago install argonaut` but `argonaut-generic` is not a dependency of `argonaut` so this isn’t actually possible.

**Describe the solution you'd like**
We should either remove the instruction or add `argonaut-generic` to the dependencies of `argonaut`.

**Comment by thomashoneyman** [comment]
Oh, that’s a good point — we should remove the instruction.
