### ISSUE TITLE
Drop the Rep suffix from modules names?

### ISSUE THREAD

**Issue by kl0tl** [purescript-contrib/purescript-argonaut-generic#32]
We renamed the Data.Generic.Rep.* modules to Data.*.Generic when porting generics-rep to prelude in https://github.com/purescript/purescript-prelude/pull/235, so we should probably rename Data.Argonaut.Decode.Generic.Rep to Data.Argonaut.Decode.Generic, Data.Argonaut.Encode.Generic.Rep to Data.Argonaut.Encode.Generic and Data.Argonaut.Types.Generic.Rep to Data.Argonaut.Types.Generic when dropping generics-rep and updating the prelude dependency to its latest version.

**Comment by thomashoneyman** [comment]
Yes; this seems like a good idea. Could you also add that change to the CHANGELOG?

**Comment by harryprayiv** [comment]
You should also update the ReadMe accordingly.  As a labrador retreiver with a keyboard, figuring out how to import Rep took me half the day.
Here's what I ended up with:
```
import Data.Argonaut.Decode.Class (class DecodeJson)
import Data.Argonaut.Decode.Generic (class DecodeRep, genericDecodeJson)
import Data.Argonaut.Encode.Class (class EncodeJson)
import Data.Argonaut.Encode.Generic (genericEncodeJson)
import Data.Argonaut.Encode.Generic (class EncodeRep, genericEncodeJson)
import Data.Generic.Rep (class Generic)
import Data.Maybe (Maybe)
```
