### ISSUE TITLE
PureScript 0.12

### ISSUE THREAD

**Issue by CarstenKoenig** [purescript-contrib/purescript-argonaut-generic#7]
starting with *v0.12* `purescript-generics` will no longer be supported by the compiler/deriving but `purescript-generics-rep` still is.

The later removed support for rows/records though and it seems `RowToList` is the way to go.

We need a way to deal with this in order for this lib to keep being usable after people switch to 0.12 or higher

**Comment by thomashoneyman** [comment]
Closing as #8 has been merged to update this library to 0.12.
